More error codes added;slight code refactor/cleanup while doing so

diff --git a/usr/bin/tinybashserver b/usr/bin/tinybashserver
--- a/usr/bin/tinybashserver
+++ b/usr/bin/tinybashserver
@@ -6,7 +6,7 @@ DOCROOT=${DOCROOT:-"/var/www/"}
 DEFAULT_INDEX=${DEFAULT_INDEX:-"index.html"}
 
 function parseHttpRequest(){
-read request
+read init_req_line
 local line=''
 while /bin/true; do
   read line
@@ -15,26 +15,30 @@ while /bin/true; do
 done
 header="${header#??}"
 
-echo "$request" | grep -qi "POST"
-if [ $? -eq 0 ];then		# POST type; get message body & set var $type
+#echo "$init_req_line" | grep -qi "POST"
+#if [ $? -eq 0 ];then		# POST type; get message body & set var $type
+if [[ "$init_req_line" =~ ^POST ]];then
 	type="POST"
-	while /bin/true; do
-	  read line
-	  [ "$line" == $'\r' -o "$line" == '' ] && break;
-	  body="$body\n$line"
-	done
+	#~ body=''
+	#~ while /bin/true;do
+		#~ read -n 1 c;
+		#~ [ "$c" == '' ] && break;
+		#~ body="$body$c"
+	#~ done
 	body="${body#??}"
-else 			# GET type; set var $type
+elif [[ "$init_req_line" =~ ^GET ]] ;then			# GET type; set var $type
 	type="GET"
+else
+	type=""
 fi
 }
 function parseRequestUrl(){
 	query_str=''
 	if [ "$type" == "POST" ];then		# POST
-		url="${request#POST }"
+		url="${init_req_line#POST }"
 		query_str="$body"		
 	else 						# GET
-		url="${request#GET }"
+		url="${init_req_line#GET }"
 		echo "$url" | grep -q "?"
 		[ $? -eq 0 ]  && query_str="${url/*\?/}"
 	fi
@@ -52,13 +56,40 @@ function createVariableString(){
 	var_str="DOCUMENT_ROOT=\"$DOCROOT\"&&HTTP_HOST=\"$hn\"&&HTTP_USER_AGENT=\"$ua\"&&QUERY_STRING=\"$query_str\"&&REQUEST_METHOD=\"$type\"&&REQUEST_URI=\"$url\""
 }
 
-
+function commonHeader(){
+	echo -e "HTTP/1.0 $1 $2"	
+	echo -e "Date:" `date`
+	echo -e "Server: Tiny Bash Server"
+}
 function aboutMe(){
 	local v1=`echo -e "$header"|grep "^Host"`
 	local hn="${v1#*:}"	
 	echo -e "<br/><br/><hr/><i>Tiny Bash Server running at" ${hn:-`hostname`} "</i>"
 }
 
+function errorResponse(){
+	local code="$1"
+	local err=""
+	local msg="The request couldn't be processed by this server"
+	case "$code" in
+		400) err="Bad Request";msg="Your browser sent a request that this server could not understand.";;
+		403) err="Forbidden";msg="You do not have permissions to access the requested resource";;
+		404) err="Not Found";msg="The requested resource was not found on this server";;
+		500) err="Internal Server Error";;
+		501) err="Not Implemented";;
+		*)   err="Internal Server Error";;
+	esac
+	commonHeader "$code" "$err"
+	cat <<EOF
+Content-Type: text/html
+
+<head> <title> $code $err </title> </head>
+<h1> $code $err </h1> 
+$msg
+EOF
+	aboutMe
+	echo -e "\r"
+}
 ## Main
 parseHttpRequest
 parseRequestUrl
@@ -68,54 +99,47 @@ filename="$DOCROOT$url"
 if [ -d "$filename" ];then
 	filename="$filename/$DEFAULT_INDEX"
 fi
-# Decide & send repsonse
+# Is there an error?
+if [ -z "$type" ];then
+	errorResponse "400"
+	exit 400
+fi
 if [ ! -f "$filename" ];then
-	echo -e "HTTP/1.0 404 Not Found\r"
-	echo -e "Date:" `date`
-	echo -e "Content-Type: text/html\r"
-	echo -e "\r"
-	echo -e "<h1>404 Not Found</h1>\r"
-	echo -e "The requested resource was not found\r"
-	aboutMe
-	echo -e "\r"
-elif [ -r "$filename" ];then
-	echo -e "HTTP/1.1 200 OK\r"
-	echo -e "Date:" `date`
-	case "${filename##*.}" in
-		"htsh") echo -e "Content-Type: text/html\r"
-				echo -e "\r"
-				/usr/bin/htsh "$filename" "`echo $var_str`"
-		;;
-		"sh") 	echo -e "Content-Type: text/html\r"
-				echo -e "\r"
-				/bin/bash "$filename" "`echo $var_str`"
-		;;
-		"html") echo -e "Content-Type: text/html\r"
-				echo -e "\r"
-				cat "$filename"		
-		;;
-		"php")  echo -e "Content-Type: text/html\r"
-				echo -e "\r"
-				/usr/bin/php "$filename" "`echo $var_str`"
-		;;
-		"py")  echo -e "Content-Type: text/html\r"
-				echo -e "\r"
-				/usr/bin/python "$filename"		
-		;;
-		*)	echo -e "Content-Type: `/usr/bin/file -bi \"$filename\"`\r"
+	errorResponse "404"
+	exit 404
+fi
+if [ ! -r "$filename" ];then
+	errorResponse "403"
+	exit 403
+fi
+# All ok
+commonHeader "200" "OK"
+case "${filename##*.}" in
+	"htsh") echo -e "Content-Type: text/html\r"
 			echo -e "\r"
-			cat "$filename"
-		;;
-	esac
-else
-	echo -e "HTTP/1.0 403 Forbidden\r"
-	echo -e "Date:" `date`
-	echo -e "Content-Type: text/html\r"
-	echo -e "\r"
-	echo -e "<h1>403 Forbidden</h1>\r"
-	echo -e "You do not have permissions to access the requested resource\r"
-	aboutMe
-	echo -e "\r"	
-fi	
+			echo "$body"------
+			/usr/bin/cgibash "$filename" "`echo $var_str`"				
+	;;
+	"sh") 	echo -e "Content-Type: text/html\r"
+			echo -e "\r"
+			/bin/bash "$filename" "`echo $var_str`"
+	;;
+	"html") echo -e "Content-Type: text/html\r"
+			echo -e "\r"
+			cat "$filename"		
+	;;
+	"php")  echo -e "Content-Type: text/html\r"
+			echo -e "\r"
+			/usr/bin/php "$filename" "`echo $var_str`"
+	;;
+	"py")  echo -e "Content-Type: text/html\r"
+			echo -e "\r"
+			/usr/bin/python "$filename"		
+	;;
+	*)	echo -e "Content-Type: `/usr/bin/file -bi \"$filename\"`\r"
+		echo -e "\r"
+		cat "$filename"
+	;;
+esac
 
 exit 0
